A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken import views as auth_token

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegister.as_view()),
    path('api-token-auth/', auth_token.obtain_auth_token),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns =[
    path('', views.HomeView.as_view(), name='home'),
    path('questions/', views.QuestionListView.as_view()),
    path('question/create/', views.QuestionCreateView.as_view()),
    path('question/update/<int:pk>/', views.QuestionUpdateView.as_view()),
    path('question/delete/<int:pk>/', views.QuestionDeleteView.as_view()),
]    

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=30)
    age = models.PositiveSmallIntegerField()
    email = models.EmailField()

    def __str__(self):
        return self.name
    

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="questions")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user} - {self.title[:20]}'
    

class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="answers")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="answers")
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user} - {self.question.title[:20]}'

accounts/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializer import UserRegisterSerializer
from rest_framework import status
# Create your views here.

class UserRegister(APIView):
    def post(self, request):
        ser_data = UserRegisterSerializer(data=request.POST)
        if ser_data.is_valid():
            ser_data.create(ser_data.validated_data)
            return Response(ser_data.data, status=status.HTTP_201_CREATED)
        return Response(ser_data.errors, status=status.HTTP_400_BAD_REQUEST)

home/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import Person, Question, Answer
from .serializer import PersonSerilizer, QuestionSerilizer, AnswerSerilizer
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework import status
from permissions import IsOwnerORreadOnly
# Create your views here.

class HomeView(APIView):
    permission_classes = [IsAuthenticated,]
    def get(self, request):
        persons = Person.objects.all()
        ser_data = PersonSerilizer(instance=persons, many=True)
        return Response(data=ser_data.data)


class QuestionListView(APIView):
    def get(self, request):
        questions = Question.objects.all()
        srz_data = QuestionSerilizer(instance=questions, many=True).data
        return Response(srz_data, status=status.HTTP_200_OK)
    
    
class QuestionCreateView(APIView):
    permission_classes = [IsAuthenticated,]

    def post(self, request):
        srz_data = QuestionSerilizer(data=request.data)
        if srz_data.is_valid():
            srz_data.save()
            return Response(srz_data.data, status=status.HTTP_201_CREATED)
        return Response(srz_data.errors, status=status.HTTP_400_BAD_REQUEST)
    
class QuestionUpdateView(APIView):
    permission_classes = [IsOwnerORreadOnly]

    def put(self, request, pk):
        question = Question.objects.get(pk=pk)
        self.check_object_permissions(request, question)
        srz_data = QuestionSerilizer(instance=question, data=request.data, partial=True)
        if srz_data.is_valid():
            srz_data.save()
            return Response(srz_data.data, status=status.HTTP_200_OK)
        return Response(srz_data.errors, status=status.HTTP_400_BAD_REQUEST)

class QuestionDeleteView(APIView):
    permission_classes = [IsOwnerORreadOnly]
    def delete(self, request, pk):
        question = Question.objects.get(pk=pk)
        self.check_object_permissions(request, question)
        question.delete()
        return Response({'message':'question deleted'}, status=status.HTTP_200_OK)

home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}
    <h3>Home</h3>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rest</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        .jumbotron{
            padding: 20px;
            margin-bottom: 20px;
            background-color: #e9ecef;
        }
    </style>
</head>
<body>

    {% include 'inc/navbar.html' %}
    <div class="jumbotron">
        {% include 'inc/messages.html' %}
        {% block content %} {% endblock %}
    </div>

</body>
</html>

templates/inc/messages.html
{% if messages %}

    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}

{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
        </div>
    </div>
</nav>